### ISSUE TITLE
[ALBERT]: LookupError: gradient registry has no entry for: AddV2 

### ISSUE THREAD

**Issue by wxp16** [google-research/ALBERT#100]
When run `run_classifier_with_tfhub.py`, but the training crashed.  The  error is:  
```
LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_11/layer_11/inner_group_0/LayerNorm_1/batchnorm/add_1' (op type: AddV2)
```
My tensorflow-gpu version is 1.14.0

Anyone knows the reason, pls help..
Thanks

**Comment by 0x0539** [comment]
Duplicate of #94 

Can you try using the TF-Hub modules with "/3" suffix? We regenerated them using TF 1.15 (see Jan 7 update in the readme).

**Comment by phosseini** [comment]
> Duplicate of #94
> 
> Can you try using the TF-Hub modules with "/3" suffix? We regenerated them using TF 1.15 (see Jan 7 update in the readme).

Worked for me.
