### ISSUE TITLE
[ALBERT] Checkpoints for pretrained models

### ISSUE THREAD

**Issue by SahanaRamnath** [google-research/ALBERT#103]
Hello! 
Thank you for releasing the code for Albert!
Could you upload the pre-trained checkpoints for the 4 Albert models? I would like to run ```run_squad_sp.py``` directly for finetuning on SQuAD.

Could you also release instructions on how to run SQuAD using tensorflow hub directly? (Similar to ```run_classifier_with_tfhub.py```?

Thanks in advance!

**Comment by 0x0539** [comment]
@SahanaRamnath I believe everything should be clear from the README now. Please reopen if you still have questions.
