### ISSUE TITLE
[ALBERT] Pretraining

### ISSUE THREAD

**Issue by stefan-it** [google-research/ALBERT#104]
Hi,

thanks for releasing implementation and pre-trained models for ALBERT :heart: 

I would really like to train a model from scratch - would this be possible with one v3-8 TPU 🤔. If that's possible could you also give a detailed overview of the parameters you used for training base or larger models?

I think the "training for x steps for sequence length 128 and then fine-tuning the model for a sequence length of 512" approach is not used in the paper, so could you specify the parameters for the `create_pretraining_data.py` script (because it is using a seq. length of 128 by default).

Thanks many in advance!

**Comment by 0x0539** [comment]
We recently added more documentation to the README.md regarding pretraining parameters.
Let us know if we can provide more information.
Tentatively closing
