### ISSUE TITLE
SQuAD vocab file for ALBERT

### ISSUE THREAD

**Issue by abdolence** [google-research/ALBERT#106]
Thanks for sharing great work,

The current implementation of albert/run_squad_sp.py requires a vocab file to work. 
Is it the same as for BERT pre-trained archives (https://github.com/google-research/bert)?

**Comment by 0x0539** [comment]
Added details about --spm_model_file to the README.md.
Please reopen if you are still having this issue.

**Comment by maziyarpanahi** [comment]
> Added details about --spm_model_file to the README.md.
> Please reopen if you are still having this issue.

I am sorry to ask, but where are these details? I can't find any explanation as to what's inside spm_model_file.

**Comment by 0x0539** [comment]
> > Added details about --spm_model_file to the README.md.
> > Please reopen if you are still having this issue.
> 
> I am sorry to ask, but where are these details? I can't find any explanation as to what's inside spm_model_file.

From the README:

`You can find the spm_model_file in the tar files or under the assets folder of the tf-hub module. The name of the model file is "30k-clean.model".`

**Comment by maziyarpanahi** [comment]
Thanks @0x0539 
I was looking more for what it does to see if it’s possible to implement this whole process manually in another language. 
I am already using it in tf-sentencepiece.

Thanks again.
