### ISSUE TITLE
Unknown signature default

### ISSUE THREAD

**Issue by EMBSKD** [google-research/ALBERT#110]
Getting a 'ValueError : Unknown signature default' in the latest albert_base release in TfHub. Been testing other tfhub module on my setup with no pb.
I'm on TF 2.0.0 and tf_hub 0.7.0

**Code :** 
```
hub_url = "https://tfhub.dev/google/albert_base/3"
albert_module = hub.KerasLayer(hub_url)
```

_Error:_
`ValueError: Unknown signature default in https://tfhub.dev/google/albert_base/3 (available signatures: _SignatureMap({'tokens': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x00000174088A8348>, 'tokenization_info': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x00000174100BA348>, 'mlm': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x000001740ECFB708>})).`

**Comment by 0x0539** [comment]
We usually use the signature called "tokens", not the default signature. See example usage here: https://github.com/google-research/ALBERT#pre-trained-models
