### ISSUE TITLE
[ALBERT] hub module on tpu

### ISSUE THREAD

**Issue by seongwook-ham** [google-research/ALBERT#117]
when i finetune hub module(version 3) with classifer.py on in mnli-m(glue), it throw follwing error
`tf hub Failed to get matching files on /tmp/tfhub_modules/xxxxxxxxxxxxx /variables/variables: Unimplemented: File system scheme '[local]' not implemented`
i think it is due to fact that tmp folder is made on local machine, but for tpu checkpoint path should be on cloud storage bucket.
uploading hub module on google storage and run classifier with hub module on cloud storage solve problem but i think it it is not convinient way.

**Comment by theword** [comment]
> when i finetune hub module(version 3) with classifer.py on in mnli-m(glue), it throw follwing error
> `tf hub Failed to get matching files on /tmp/tfhub_modules/xxxxxxxxxxxxx /variables/variables: Unimplemented: File system scheme '[local]' not implemented`
> i think it is due to fact that tmp folder is made on local machine, but for tpu checkpoint path should be on cloud storage bucket.
> uploading hub module on google storage and run classifier with hub module on cloud storage solve problem but i think it it is not convinient way.

I am running into this problem. What did you do  to fix it? You created a tmp folder on Google storage and put the 3 folder in it? (the untar hub module 3.tar.gz)

**Comment by 0x0539** [comment]
I haven't tested this, but you may be able to simply set TFHUB_CACHE_DIR to a gs bucket where you have read+write access. See https://www.tensorflow.org/hub/api_docs/python/hub/load.

If I understand correctly, tensorflow_hub will cache hub files there. No need to upload files there manually.

**Comment by 0x0539** [comment]
(please reopen if you still have issues)

**Comment by theword** [comment]
> I haven't tested this, but you may be able to simply set TFHUB_CACHE_DIR to a gs bucket where you have read+write access. See https://www.tensorflow.org/hub/api_docs/python/hub/load.
> 
> If I understand correctly, tensorflow_hub will cache hub files there. No need to upload files there manually.

Just setting --albert_hub_module_handle='gs://mygooglebucket/3' worked.

**Comment by ctmckee** [comment]
I am running into the same problem.  Could you please describe solution in detail.  I have set the "--albert_hub_module_handle='gs://someGoogleBucket/anEmptyFolder'".  Do I need to put the 3.tar.gz folder (unzipped) in the "anEmptyFolder" ?

**Comment by theword** [comment]
> I am running into the same problem. Could you please describe solution in detail. I have set the "--albert_hub_module_handle='gs://someGoogleBucket/anEmptyFolder'". Do I need to put the 3.tar.gz folder (unzipped) in the "anEmptyFolder" ?

Unzip the 3.tar.gz file into your Google Cloud Storage. Then have the --albert_hub_module_handle point to the directory that you unzipped.
