### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[32,512,3072] and type float on

### ISSUE THREAD

**Issue by MaybeLL** [google-research/ALBERT#119]
i have trouble with run the run_race.py. I google it and decrease the --train_batch_size from 32 to 8,but it didn't work.
i use a GTX 1660TI with cuda10.
here is my parameter:
--albert_config_file=/home/dy/Project/ALBERT/albert_base/albert_config.json
--output_dir=/home/dy/Project/ALBERT/output_dir
--data_dir=/home/dy/Project/ALBERT
--init_checkpoint=/home/dy/Project/ALBERT/albert_base/model.ckpt-best
--train_file=/home/dy/Project/ALBERT/train_file/train
--eval_file=/home/dy/Project/ALBERT/eval_file/eval
--vocab_file=/home/dy/Project/ALBERT/albert_base/30k-clean.vocab
--spm_model_file=/home/dy/Project/ALBERT/albert_base/30k-clean.model
--max_seq_length=512
--max_qa_length=128
--do_train
--do_eval
--train_batch_size=8
--eval_batch_size=8
--learning_rate=1e-5
--train_step=12000
--warmup_step=1000
--save_checkpoints_steps=100
if you need know anything orther,just let me know.
im appreciate any help!

**Comment by MaybeLL** [comment]
> i have trouble with run the run_race.py. I google it and decrease the --train_batch_size from 32 to 8,but it didn't work.
> i use a GTX 1660TI with cuda10.
> here is my parameter:
> --albert_config_file=/home/dy/Project/ALBERT/albert_base/albert_config.json
> --output_dir=/home/dy/Project/ALBERT/output_dir
> --data_dir=/home/dy/Project/ALBERT
> --init_checkpoint=/home/dy/Project/ALBERT/albert_base/model.ckpt-best
> --train_file=/home/dy/Project/ALBERT/train_file/train
> --eval_file=/home/dy/Project/ALBERT/eval_file/eval
> --vocab_file=/home/dy/Project/ALBERT/albert_base/30k-clean.vocab
> --spm_model_file=/home/dy/Project/ALBERT/albert_base/30k-clean.model
> --max_seq_length=512
> --max_qa_length=128
> --do_train
> --do_eval
> --train_batch_size=8
> --eval_batch_size=8
> --learning_rate=1e-5
> --train_step=12000
> --warmup_step=1000
> --save_checkpoints_steps=100
> if you need know anything orther,just let me know.
> im appreciate any help!

by the way,what does max_qa_length mean? is there any different bettwen max_seq_length and max_qa_length?

**Comment by 0x0539** [comment]
Resource exhausted means you do not have enough memory on your device.

[32,512,3072] indicates that your batch size is 32, which is the default. Are you sure that your flags are being passed to run_race.py correctly?

See run_race.py for definition of `max_qa_length`:

```
flags.DEFINE_integer(
    "max_qa_length", 128,
    "The maximum total input sequence length after WordPiece tokenization. "
    "Sequences longer than this will be truncated, and sequences shorter "
    "than this will be padded.")
```

**Comment by MaybeLL** [comment]
very thank you for your reply. i have checked the flags,but finding nothing wrong as i see .
i try to clear the output_dir and try to run run_race.py again. it turn out to a new error as following:
`Traceback (most recent call last):
  File "/home/dy/Project/ALBERT/run_race.py", line 457, in <module>
    tf.app.run()
  File "/home/dy/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/dy/anaconda3/envs/albert/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/dy/anaconda3/envs/albert/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/dy/Project/ALBERT/run_race.py", line 260, in main
    FLAGS.train_file, FLAGS.max_qa_length)
  File "/home/dy/Project/ALBERT/race_utils.py", line 263, in file_based_convert_examples_to_features
    max_seq_length, tokenizer, max_qa_length)
  File "/home/dy/Project/ALBERT/race_utils.py", line 233, in convert_single_example
    tf.logging.info("tokens: {}".format(" ".join(tokens)))
TypeError: sequence item 373: expected str instance, bytes found

Process finished with exit code 1
`
before fix this error, i want to assure  what is the **all.txt** file in RACE dataset exactly is?
i can't find it in RACE dataset .i download the RACE dataset at [race](http://www.cs.cmu.edu/~glai1/data/race/)

here is the all.txt how it be used in **race_utils.py**:

  def read_examples(self, data_dir):
    """Read examples from RACE json files."""
    examples = []
    for level in ["middle", "high"]:
      if level == "middle" and self.high_only: continue
      if level == "high" and self.middle_only: continue
      cur_dir = os.path.join(data_dir, level)

      cur_path = os.path.join(cur_dir, "all.txt")
      with tf.gfile.Open(cur_path) as f:
        for line in f:
          cur_data = json.loads(line.strip())

          answers = cur_data["answers"]
          options = cur_data["options"]
          questions = cur_data["questions"]
          context = self.process_text(cur_data["article"])

          for i in range(len(answers)):
            label = ord(answers[i]) - ord("A")
            qa_list = []

            question = self.process_text(questions[i])
            for j in range(4):
              option = self.process_text(options[i][j])

              if "_" in question:
                qa_cat = question.replace("_", option)
              else:
                qa_cat = " ".join([question, option])

              qa_list.append(qa_cat)

            examples.append(
                InputExample(
                    example_id=cur_data["id"],
                    context_sentence=context,
                    start_ending=None,
                    endings=[qa_list[0], qa_list[1], qa_list[2], qa_list[3]],
                    label=label
                )
            )

    return examples

**Comment by MaybeLL** [comment]
i have solved the error.i set the batch_size to 1,then the error has disappered . At the beginning,i set the batch_size = 4,it didn't work,so i thought it is not the batch_size problem
