### ISSUE TITLE
Adding new custom tokens in vocab during the fine-tuning pre-trained model

### ISSUE THREAD

**Issue by igeti** [google-research/ALBERT#122]
I want to add new tokens to the dictionary when fine-tuning the pre-trained Albert model. For example, in Bert, we can insert new custom tokens into the dictionary in place of [unknown] tokens:
[PAD]
[unused0]
[unused1]
[unused2]
[unused3]
[unused4]
...
But in Albert, I did not find such an opportunity, since the dictionary(30k-clean.vocab) is completely filled.

**Comment by dem-esgal** [comment]
As I have noted here [https://github.com/google-research/ALBERT/issues/127](url)
ALBERT vocab uses the same value for completely different tokens:
▁falcon	-11.6322
▁kla	-11.6322
▁oslo	-11.6322
So I think that you can just add you token to the dict with one of existing values.

**Comment by 0x0539** [comment]
See https://github.com/google-research/ALBERT/issues/127#issuecomment-581869983 for how to do this.
