### ISSUE TITLE
ALBERT vocabulary and BERT vocabulary

### ISSUE THREAD

**Issue by zzj0402** [google-research/ALBERT#127]
I am trying to make TFRecords for Natural Question dataset. The vocabulary of ALBERT differs dramatically with BERT's:

bert-joint-baseline's vocab-nq.txt
```
[PAD]
[unused0]
[unused1]
[unused2]
[unused3]
[unused4]
[unused5]
```

albert-base's 30k-clean.vocab
```
<pad>   0
<unk>   0
[CLS]   0
[SEP]   0
[MASK]  0
(       0
)       0
"       0
-       0
.       0
```

How to prepare  Natural Language dataset for ALBERT?

**Comment by dem-esgal** [comment]
I also note that ALBERT vocab uses the same value for completely different tokens:
▁falcon	-11.6322
▁kla	-11.6322
▁oslo	-11.6322

**Comment by maziyarpanahi** [comment]
I am a bit confused about the vocabulary as well. The naming convention aside (which is vocab.txt in all BERT pretrained models), there are two columns in ALBERT's vocab. I am loading it from TF Hub and saving it as a Bundle for Java and this is an unusual vocabulary considering everything else is identical to BERT.
Is there any way to convert this 30k-clean.vocab to BERT-style vocab.txt?

**Comment by zanderkent** [comment]
> UPDATE: The vocab is different because ALBERT uses sentencepiece!

Do you know how do update the sentencepeice model for domain specific words? In BERT you would just add it to the vocab dictionary before passing it to the tokenizer.

**Comment by maziyarpanahi** [comment]
That is a very good question! Unfortunately i haven’t reached that far yet and trying to implement sentence piece in Java, but I would really like to know the answer. 
(One guess is to use sentence piece to generate new vocabs, and probably a new spm model file but I would like to know if that would work with ALBERT)

**Comment by zanderkent** [comment]
I'm looking into it right now, if I remember I will post what I find out here!

**Comment by dem-esgal** [comment]
Please look at this thread:
https://github.com/google/sentencepiece/issues/323
for how to add a token.
You can also use this thread to validate a vocab:
https://github.com/google/sentencepiece/issues/328

**Comment by 0x0539** [comment]
See https://github.com/google-research/ALBERT/issues/127#issuecomment-581869983 for the resolution.
