### ISSUE TITLE
How can I view model weights ?

### ISSUE THREAD

**Issue by pzdkn** [google-research/ALBERT#145]
I observe that the finetuned model makes the same predictions for all instances. I wanted to view the weights to validate. How would I do this ?

**Comment by 0x0539** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py

**Comment by pzdkn** [comment]
thanks a lot

**Comment by pzdkn** [comment]
thanks a lot
