### ISSUE TITLE
Provide the parameters used for the sentencepiece 

### ISSUE THREAD

**Issue by 0x0539** [google-research/ALBERT#149]
Hi @Danny-Google,
When training our own sentencepiece model, do the parameters used for it's training matter? Should it be enough to just specify a vocab_size, control_symbols=[CLS],[SEP],[MASK], and use the default 'unigram' model_type? 
Is it possible to provide the parameters used for the sentencepiece used for the training of these ALBERT models?
Thanks!

_Originally posted by @pvcastro in https://github.com/google-research/ALBERT/issues/50#issuecomment-570327554_

**Comment by Danny-Google** [comment]
Hi Sebastian, here is the command we used to generate the spm vocab model.

spm_train \
--input all.txt --model_prefix=30k-clean --vocab_size=30000 --logtostderr\
--pad_id=0 --unk_id=1 --eos_id=-1 --bos_id=-1\
--control_symbols=[CLS],[SEP],[MASK] \
--user_defined_symbols=\(,\),\”,-,.,–,£,€\
--shuffle_input_sentence=true --input_sentence_size=10000000\
--character_coverage=0.99995 --model_type=unigram

**Comment by ngoanpv** [comment]
I think you should add that command that you used to generate the spm vocab model in README.

**Comment by Danny-Google** [comment]
@ngoanpv Done, thanks for the suggestions

**Comment by pvcastro** [comment]
Thanks!
