### ISSUE TITLE
a question about `num_attention_heads`

### ISSUE THREAD

**Issue by beamind** [google-research/albert#153]
According to part 3.1 of paper, for xxlarge model,  the `num_attention_heads`=H/64=4096/64=64. But according to `albert_config.json` file from `albert_xxlarge_zh.tar.gz`, the `num_attention_heads`=16. So which is correct? Thanks!

**Comment by akakakakakaa** [comment]
4096 is intermediate size not hidden size.

**Comment by beamind** [comment]
> 4096 is intermediate size not hidden size.

for xxlarge, "hidden_size": 4096,  "intermediate_size": 16384. This is from albert_config.json file from albert_xxlarge_zh.tar.gz

**Comment by akakakakakaa** [comment]
Sorry, I checked.

When I downloaded v2 version, num_attention_heads is 64.

**Comment by Danny-Google** [comment]
yes, we later found that 16 heads give better performance and switch to 16 heads in zh version.  Our new paper about talking heads should fix the problem that more heads gives worse performance (https://arxiv.org/abs/2003.02436).
