### ISSUE TITLE
When I ran the file ‘run_pretraining.py’, there was a problem

### ISSUE THREAD

**Issue by bigzhouj** [google-research/ALBERT#166]
running on Windows：
‘ERROR:tensorflow:Error recorded from training_loop: corrupted record at 0
	 [[node IteratorGetNext (defined at C:\Users\root\Anaconda3\envs\albert\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
Original stack trace for 'IteratorGetNext':’

**Comment by gjamesli2126** [comment]
How did you solve it?

**Comment by bigzhouj** [comment]
> How did you solve it?
It seems to be the version，It's too long to remember。

**Comment by gjamesli2126** [comment]
Thank you for your quick reply!
I will work on it.

**Comment by gjamesli2126** [comment]
May I have your pip freeze for that?
I have done "pip install -r albert/requirements.txt" but still the same.
Thanks a lot!

**Comment by bigzhouj** [comment]
> May I have your pip freeze for your project?
> I have done "pip install -r albert/requirements.txt" but still the same.
> Thanks a lot!

This project has been modified many times, and Albert is no longer used。I'm very sorry about this.

**Comment by gjamesli2126** [comment]
It's ok.
Thanks for your reply!
