### ISSUE TITLE
Running run_classifier.py error

### ISSUE THREAD

**Issue by junrong1** [google-research/albert#169]
I use windows 10
tensorflow-gpu 1.15.0
CuDA v10.0
python 3.6.1

I0224 12:28:21.370724 23132 tokenization.py:240] loading sentence piece model
W0224 12:28:21.669923 23132 module_wrapper.py:139] From C:\Users\Junrong Yao\Desktop\ALBERT\classifier_utils.py:115: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

Windows fatal exception: access violation

**Comment by lzw429** [comment]
I'm experiencing the same issue and have no idea how to fix it.
Does anyone know the solution?

**Comment by ibrahimishag** [comment]
> I'm experiencing the same issue and have no idea how to fix it.
> Does anyone know the solution?

If you or someone else is still getting this error, I ran into this error and resolved it by matching the data_dir to the processors in the run_classifier.py code.

I hope this will help someone!.
