### ISSUE TITLE
How to continue train ALBERT from the modelreleased on the tfhub ?

### ISSUE THREAD

**Issue by wxp16** [google-research/ALBERT#17]
Training from scratch is very expensive.  Anybody know how to  continue train ALBERT from the exported model..

Thanks

**Comment by 0x0539** [comment]
Note that the TF-Hub checkpoints do not contain LAMB optimizer momentum estimates, so it won't be exactly the same as resuming from training. In particular, the momentum estimates will be reset to zero.

That said, it's still probably faster than starting from a randomly-initialized ALBERT :)

If you want to try it, I can think of two ways:

1) Extract the checkpoint files manually from the TF-Hub module. Look inside the variables/ folder. These files can be copied into your training dir as the .data and .index files of a checkpoint. You may need to create a file called `checkpoint` that points to them (look inside an ALBERT training directory for the format).
2) Add a flag to `run_pretraining.py` for initializing from TF-Hub. It should be similar to [this recent commit](https://github.com/google-research/ALBERT/commit/941051a5c8ef2274fe7bc698b0aac94e281db2e7), which did the same thing but for `run_classifier.py`. If you want to put together a PR for this, that'd really be helpful.

**Comment by 0x0539** [comment]
There's an easier way to get these checkpoints now. See the `[Tar file]` links in the readme.
