### ISSUE TITLE
File system scheme '[local]' not implemented (fine tuning Albert on TPU)

### ISSUE THREAD

**Issue by ctmckee** [google-research/albert#173]
I am running into the same problem.  Could you please describe solution in detail.  I have set the "--albert_hub_module_handle='gs://someGoogleBucket/anEmptyFolder'".  Do I need to put the 3.tar.gz folder (unzipped) in the "anEmptyFolder" ?

_Originally posted by @ctmckee in https://github.com/google-research/ALBERT/issues/117#issuecomment-593651950_

**Comment by Danny-Google** [comment]
You should set the os environment to point to your cloud bucket. Please check out this tutorial.
