### ISSUE TITLE
ModuleNotFoundError: No module named 'albert'

### ISSUE THREAD

**Issue by elliotthwang** [google-research/albert#199]
Traceback (most recent call last):
  File "/content/squad_base_dir/run_squad_v1.py", line 27, in <module>
    from albert import fine_tuning_utils
ModuleNotFoundError: No module named 'albert'

Please help!

**Comment by gongel** [comment]
Just change "from albert import fine_tuning_utils" to "import fine_tuning_utils"

**Comment by clrajapaksha** [comment]
You should run this from outside of albert directory. No need to change the source code

**Comment by elliotthwang** [comment]
@gongel  @clrajapaksha 
Thank a lot!
