### ISSUE TITLE
Will you release Chinese albert models ?

### ISSUE THREAD

**Issue by ljch2018** [google-research/ALBERT#20]
Thanks.

**Comment by siyu828** [comment]
same question，we are waiting for that,thanks

**Comment by peregilk** [comment]
There are some unofficial Chinese weights available here: https://github.com/brightmart/albert_zh

**Comment by Danny-Google** [comment]
Yes, we have the models trained, will release it soon. Please stay tuned.

**Comment by hankcs** [comment]
We've been waiting from 2019 to 2020 ...😁

**Comment by Danny-Google** [comment]
Done. Thanks for pressuring us!

**Comment by hankcs** [comment]
> Done. Thanks for pressuring us!

Thank you so much! The best new year gift I've ever received.

**Comment by Danny-Google** [comment]
> > Done. Thanks for pressuring us!
> 
> Thank you so much! The best new year gift I've ever received.

Oh, thank you so much! I am flattered!

**Comment by like4hub** [comment]
waiting for it

**Comment by 0x0539** [comment]
Closing for now. Please see the readme for details.
