### ISSUE TITLE
export_dir in run_pretraining.py is necessary?

### ISSUE THREAD

**Issue by tomohideshibata** [google-research/ALBERT#21]
`export_dir` is just made at L545 in `run_pretraining.py`, but nothing else happens.

```python
tf.gfile.MakeDirs(FLAGS.export_dir)
```

In the current script, unless `--export_dir` option is specified, the script dies in the evaluation step. 
`export_dir` is necessary?

**Comment by Danny-Google** [comment]
Yes, it is required.

**Comment by tomohideshibata** [comment]
But, it seems nothing is outputted under `export_dir`.

**Comment by Danny-Google** [comment]
Good catch! Have submitted a change. Should be out soon. Thanks a lot!

**Comment by tomohideshibata** [comment]
Thanks for your quick response!
In addition to `run_pretraining.py`, please remove `export_dir` from `README.md`, `run_pretraining_test.py` and `run.sh`.

Thanks.

**Comment by lanzhzh** [comment]
fixed. Thanks!
