### ISSUE TITLE
How to prepare for the environment/data for fine-tuning? 

### ISSUE THREAD

**Issue by 517030910405** [google-research/albert#216]
I am trying to run `run_glue.sh` for COLA. 
I downloaded the model from "https://tfhub.dev/google/albert_base/3", because the server cannot access google. 
However, I found that `vocab.txt` is not in the folder. 
Where should I get it? 
Also, I found that the program started to download even if the model `albert_base_3.tar.gz` is there. 
How to use local model? 
Thank you very much!

**Comment by 517030910405** [comment]
Is there an example of how should I organize the folders? 
Thanks

Maybe something like: 

-ALBERT
--albert_base_3
---saved_model.pb
--CoLA
---dev.tsv
---train.tsv
---train.tsv

**Comment by lzw429** [comment]
I have the same question and have no idea how to organize the data. It seems nowhere mentioned the method to construct the fine-tuning data.
