### ISSUE TITLE
Empty predictions in SQUAD2.0 fine tuning

### ISSUE THREAD

**Issue by skubicius** [google-research/ALBERT#25]
Hi,

I'm trying to reproduce SQUAD fine tuning using this command:

python ALBERT/run_squad_sp.py \
--albert_config_file=albert_pretrained_assets/assets/albert_config.json \
--vocab_file=$ALBERT_LARGE_DIR/assets/30k-clean.vocab \
--spm_model_file=albert_pretrained_assets/assets/30k-clean.model \
--output_dir=$ALBERT_LARGE_DIR/output \
--train_file=$SQUAD_DIR/train-v2.0.json \
--predict_file=$SQUAD_DIR/dev-v2.0.json \
--train_feature_file=$ALBERT_LARGE_DIR/train.tfrecord \
--predict_feature_file=$ALBERT_LARGE_DIR/dev.tfrecord \
--init_checkpoint=$ALBERT_LARGE_DIR/albert_pretrained_assets/variables/variables \
--do_train \
--do_predict \
--use_tpu=True \
--tpu_name=$TPU_ADDRESS \
--train_batch_size=32 \
--predict_batch_size=8 \
--learning_rate=3e-5 \
--num_train_steps=3 \
--predict_feature_left_file=pred_left_file.pkl \
--version_2_with_negative=True

I take the pretrained assets from here:
https://storage.googleapis.com/tfhub-modules/google/albert_xxlarge/2.tar.gz

The only adjustment I'm doing to the code is this;
https://github.com/google-research/ALBERT/issues/6#issuecomment-566039948

The training completes fine, but all the predictions on the dev set are empty.
Below is an example of one of my raw predictions (start/end logits and input ids).

Do these look plausible and there is some issue with postprocessing?
Or are these logits likely not coming from a good model?

{'unique_ids': 1000000250, 'start_logits': array([ 32.492077  ,  -4.7702384 ,  -5.3071485 ,  -7.3531575 ,
        -7.293605  ,  -1.3561314 ,  -6.9916544 ,  -8.323491  ,
        -8.475444  ,  -7.4066014 ,  -2.4582055 ,  -6.273889  ,
        -3.7284265 ,  32.49204   ,  -7.5345755 ,  -5.772109  ,
        -6.403943  ,  -7.8534036 ,  -7.380982  ,  -8.736341  ,
        -8.716504  ,  -8.595491  ,  -8.828945  , -10.291593  ,
       -10.899538  ,  -8.566535  ,  -9.116421  ,  -9.441428  ,
       -11.066465  ,  -8.4159155 , -10.099936  ,  -9.960946  ,
       -10.167872  ,  -5.4684653 ,  -8.753982  ,  -8.188157  ,
        -5.693802  ,  -9.302214  , -10.403065  ,  -9.081882  ,
        -7.457605  ,  -7.3181844 ,  -9.493667  ,  -5.9238324 ,
        -9.697893  ,  -9.997058  ,  -9.427417  ,  -9.136994  ,
       -10.145683  ,  -9.23794   ,  -9.477319  ,  -9.643192  ,
        -8.334411  ,  -9.444142  ,  -9.6335535 ,  -9.837363  ,
        -9.043205  ,  -9.8156805 ,  -6.29545   ,  -8.995392  ,
        -5.2824373 ,  -1.2501358 ,  -8.290365  ,  -9.415461  ,
       -10.2715645 ,  -8.060668  ,  -9.529502  ,  -8.725435  ,
        -8.435248  ,  -9.03744   ,  -8.996275  ,  -9.750856  ,
        -6.667779  ,  -9.761398  ,   0.3095445 ,  -2.6191027 ,
        -8.949279  ,  -9.730593  ,  -8.854251  ,  -8.010062  ,
       -10.353564  ,  -9.228886  ,  -9.74172   ,  -8.046814  ,
       -10.672624  ,  -8.9382105 ,  -8.40336   ,  -6.7501483 ,
        -8.092009  , -10.333969  ,  -9.18351   ,  -9.125861  ,
       -10.196643  ,  -9.506557  ,  -9.5005    ,  -7.964651  ,
        -9.986472  , -10.9585285 ,  -7.905888  ,  -7.3293767 ,
        -4.3596067 ,  -3.6847148 ,  -8.820602  ,  -8.35854   ,
        -8.687272  ,  -9.311852  ,  -8.713814  ,  -7.7075534 ,
         2.550736  ,  -2.9395669 ,  -7.44667   ,  -7.7979894 ,
        -5.7264476 ,  -9.809712  ,  -9.329958  ,  -9.91716   ,
        -7.3133736 , -10.523984  ,  -9.530984  ,  -8.59717   ,
         0.56280684,  -9.776578  ,  -4.0872846 ,  -8.996286  ,
        -9.861519  , -10.2613    ,  -9.617529  ,  -9.556009  ,
        -9.322816  ,  -4.613512  ,  -8.694246  ,  -9.629591  ,
        -9.886489  , -10.064002  ,  -8.392533  ,  -9.974358  ,
        -8.5054865 ,  -3.5060093 , -10.603832  ,   6.117955  ,
       -10.193131  , -10.123073  ,  -9.289236  , -10.401204  ,
        -9.629402  ,  -9.36797   ,  -9.885289  ,  -9.182263  ,
        -9.749663  ,  -9.529558  ,  -8.576078  ,  -9.91628   ,
       -10.549624  ,  -8.057637  ,  -5.3007236 ,  -9.572412  ,
        -9.29101   ,  -9.346475  ,  -9.0470705 ,  -5.7339444 ,
        -7.1283274 ,  -8.454945  ,  -9.598195  ,  -8.324174  ,
        -7.5823483 ,  -6.545132  ,  -6.2996893 ,  -5.84181   ,
       -10.733965  ,  -9.259142  , -10.40802   ,  -9.271391  ,
        -8.693483  , -10.110479  ,  -9.116555  ,  -9.626215  ,
        -3.886188  ,  -9.081702  ,  -7.8628426 ,  -9.250746  ,
        -2.571162  ,  32.492672  , -10.75302   , -11.3470125 ,
       -11.323054  , -11.150279  , -10.938285  , -11.263189  ,
       -11.414168  , -11.255956  , -10.33883   , -11.423634  ,
       -11.374786  , -11.346334  , -11.236787  , -11.305362  ,
       -11.410514  , -11.599903  , -11.523354  , -11.492062  ,
       -11.317745  , -11.318671  , -11.396666  , -10.59232   ,
       -10.538756  , -11.163337  , -11.317619  , -11.429593  ,
       -11.277959  , -11.299318  , -11.278977  , -11.410748  ,
       -11.221662  , -11.344649  , -11.076778  , -10.954146  ,
       -10.739065  , -11.183723  , -11.055533  , -11.272717  ,
       -11.001307  , -10.082237  , -11.134067  , -11.350092  ,
       -11.350992  , -11.484691  , -11.55689   , -11.422671  ,
       -11.38034   , -11.229648  , -11.402718  , -11.484393  ,
       -11.474542  , -11.279149  , -11.347229  , -11.459339  ,
       -11.464872  , -11.496973  , -11.399382  , -11.329305  ,
       -11.528903  , -11.497735  , -11.143899  , -11.369284  ,
       -11.470839  , -11.410302  , -11.269416  , -11.440345  ,
       -11.3409195 , -11.267136  , -11.238742  , -11.419879  ,
       -11.39023   , -11.233756  , -11.309946  , -11.121547  ,
       -11.155107  , -10.748575  , -11.344071  , -11.550126  ,
       -11.504214  , -11.464054  , -10.636411  , -11.425609  ,
       -11.426272  , -11.274211  , -11.491046  , -10.981838  ,
       -11.099386  , -10.741527  , -11.227143  , -11.126882  ,
       -11.48062   , -11.572575  , -11.455867  , -11.478917  ,
       -11.407847  , -11.274568  , -11.57136   , -11.403845  ,
       -11.552199  , -11.305284  , -11.229379  , -11.227209  ,
       -11.405649  , -11.320697  , -11.242403  , -11.547404  ,
       -11.469126  , -11.355931  , -11.338824  , -11.39074   ,
       -11.345729  , -11.249731  , -11.143266  , -11.080775  ,
       -11.145997  , -11.197949  , -11.361992  , -11.108852  ,
       -11.319454  , -11.245691  , -10.496116  , -11.33942   ,
       -11.271452  , -11.403827  , -11.522684  , -11.283761  ,
       -11.381343  , -11.412595  , -11.211511  , -11.293068  ,
       -11.224703  , -11.092644  , -11.241481  , -11.116934  ,
       -11.218116  , -11.224928  , -10.832396  , -11.419412  ,
       -11.401228  , -11.363759  , -11.432838  , -11.242041  ,
       -11.299697  , -11.371736  , -11.00289   , -11.146893  ,
       -11.201878  , -11.314821  , -11.301463  , -11.382899  ,
       -11.266075  , -11.119357  , -11.409951  , -11.316956  ,
       -11.409808  , -11.320958  , -11.26694   , -11.0755005 ,
       -11.287143  ,  -9.686739  , -11.187291  , -10.906948  ,
       -10.854231  , -10.9102745 , -11.225242  , -11.014774  ,
       -11.119512  , -11.327267  , -11.1984825 , -11.145623  ,
       -11.148404  , -11.026664  ,  -5.958495  , -11.2801285 ,
       -11.117526  , -10.987885  , -10.72861   , -11.097619  ,
       -11.208358  , -10.981565  , -11.006988  , -10.994213  ,
       -11.246639  , -11.23378   , -11.144331  , -10.485719  ,
       -10.47072   , -10.369228  ,  -9.892218  , -11.048785  ,
        -4.745694  ,  -3.857018  ,  -9.661817  ,  -8.253712  ,
       -10.17481   , -10.800198  , -11.298898  , -11.384977  ,
       -11.38076   , -11.183654  , -10.963744  , -10.309801  ],
      dtype=float32), 'end_logits': array([13.980601 , -5.9421573, -6.2675467, -7.1004558, -7.1013193,
       -4.5275083, -6.9004474, -7.523801 , -7.3448257, -6.9857674,
       -4.7483497, -6.533005 , -5.5358586, 13.980247 , -7.372515 ,
       -6.201549 , -6.5718265, -7.4586535, -7.0114284, -7.7466974,
       -7.8764763, -7.360185 , -7.7208824, -8.435166 , -8.704425 ,
       -7.5207157, -7.9054465, -7.990888 , -8.647978 , -7.465945 ,
       -8.380616 , -8.333535 , -8.192609 , -6.4205003, -7.7471557,
       -7.502494 , -6.653397 , -7.963937 , -8.370129 , -7.60479  ,
       -6.940164 , -7.1189885, -8.059554 , -6.0465326, -8.333706 ,
       -8.237374 , -7.9004703, -7.817407 , -8.112848 , -8.0607605,
       -7.9982166, -8.236431 , -7.4191327, -7.670082 , -8.189457 ,
       -8.052254 , -7.536856 , -8.266528 , -6.8024635, -7.8543863,
       -5.9268317, -4.101945 , -7.248998 , -8.082184 , -8.19226  ,
       -7.317739 , -7.976332 , -7.7475886, -7.3307858, -7.8746557,
       -7.875618 , -8.33238  , -6.57059  , -8.032316 , -3.8080852,
       -4.4646645, -7.6558943, -8.23491  , -7.670557 , -7.383502 ,
       -8.34395  , -8.213456 , -8.072449 , -7.6227455, -8.632899 ,
       -8.19599  , -7.6262617, -7.0217676, -7.4107785, -8.31583  ,
       -8.100961 , -7.999726 , -8.368761 , -8.12259  , -7.9516044,
       -7.2010965, -8.327225 , -8.637821 , -7.3406377, -6.8946805,
       -5.8515587, -5.1791353, -7.728599 , -7.6741943, -7.818308 ,
       -7.7158628, -7.7540884, -7.058491 , -2.3756666, -4.7144985,
       -7.037941 , -7.453702 , -6.011752 , -8.208148 , -8.212811 ,
       -7.975172 , -7.13471  , -8.412979 , -8.049957 , -7.49192  ,
       -3.0511413, -7.966433 , -5.158552 , -7.944243 , -8.059891 ,
       -8.452518 , -7.862584 , -7.958085 , -8.162132 , -6.423041 ,
       -7.522089 , -7.726751 , -8.147082 , -8.352554 , -7.0619135,
       -8.221669 , -7.666401 , -5.6226244, -8.555966 , -2.1391149,
       -8.137326 , -7.832819 , -7.7725205, -8.5233345, -7.8167205,
       -8.000204 , -7.964731 , -8.034388 , -8.180072 , -7.930403 ,
       -7.2496266, -7.703709 , -8.293184 , -7.41335  , -6.3174224,
       -8.138007 , -7.913705 , -7.844788 , -7.967846 , -6.30832  ,
       -6.993759 , -7.735281 , -8.090862 , -7.608359 , -7.0676427,
       -6.508229 , -6.378992 , -6.259822 , -8.350156 , -8.017179 ,
       -8.2522135, -7.8323464, -7.876441 , -8.11695  , -7.6793146,
       -7.8867702, -5.058017 , -7.5976663, -7.6022334, -7.8224216,
       -5.1303606, 13.980069 , -8.566423 , -8.901441 , -8.853021 ,
       -8.752739 , -8.639004 , -8.904689 , -8.994235 , -8.847012 ,
       -8.690465 , -8.991169 , -8.965251 , -8.82615  , -8.667468 ,
       -8.73559  , -8.827875 , -8.944195 , -8.910872 , -8.906355 ,
       -8.869256 , -8.854221 , -8.865864 , -8.714672 , -8.720728 ,
       -8.861519 , -8.819918 , -8.850843 , -8.767699 , -8.783597 ,
       -8.945577 , -8.91487  , -8.801979 , -8.88603  , -8.728445 ,
       -8.592761 , -8.854345 , -8.803937 , -8.520086 , -8.857505 ,
       -8.855807 , -8.482559 , -8.846962 , -8.783084 , -8.795558 ,
       -8.891799 , -8.905707 , -8.765816 , -8.841355 , -8.692129 ,
       -8.845418 , -8.906701 , -8.898888 , -8.815481 , -8.8858595,
       -8.941766 , -8.920526 , -8.901926 , -8.987539 , -8.831331 ,
       -8.94895  , -8.915251 , -8.610903 , -9.0112   , -8.943382 ,
       -8.810586 , -8.81173  , -8.84083  , -8.839779 , -8.84697  ,
       -8.883424 , -8.867804 , -8.839399 , -8.900132 , -8.79996  ,
       -8.724433 , -8.821463 , -8.668339 , -8.829574 , -8.952307 ,
       -8.8882475, -8.813394 , -8.588145 , -8.895828 , -8.863983 ,
       -8.923091 , -8.9845295, -8.811109 , -8.895686 , -8.669849 ,
       -8.925668 , -8.939157 , -9.046919 , -9.102462 , -8.935375 ,
       -8.879499 , -8.857879 , -8.8100195, -8.951622 , -8.896307 ,
       -9.0584755, -8.960087 , -8.874461 , -8.877767 , -8.928325 ,
       -8.828875 , -8.885995 , -8.984813 , -8.90946  , -8.798331 ,
       -8.865766 , -8.846141 , -8.814672 , -8.931564 , -8.788016 ,
       -8.806941 , -8.823355 , -8.760348 , -8.878971 , -8.75586  ,
       -8.833899 , -8.790769 , -8.420062 , -8.820567 , -8.767237 ,
       -8.85908  , -8.91672  , -8.787272 , -8.921618 , -8.916748 ,
       -8.894114 , -9.005464 , -9.002162 , -8.7317   , -8.991172 ,
       -8.961808 , -8.858345 , -8.773042 , -8.910508 , -8.980481 ,
       -9.002332 , -8.892527 , -9.083744 , -8.98649  , -8.953339 ,
       -8.832627 , -8.849195 , -8.752328 , -8.796953 , -8.861728 ,
       -8.807137 , -8.964254 , -8.899558 , -8.635408 , -8.9118595,
       -8.894284 , -8.926756 , -8.974174 , -8.88141  , -8.589125 ,
       -8.93391  , -8.241619 , -8.855608 , -8.670885 , -8.597554 ,
       -8.62252  , -8.767728 , -8.693449 , -8.786071 , -8.889353 ,
       -8.781237 , -8.718067 , -8.75278  , -8.680971 , -6.5431957,
       -8.836733 , -8.718525 , -8.574136 , -8.585432 , -8.744406 ,
       -8.846542 , -8.647195 , -8.721322 , -8.688688 , -8.7984085,
       -8.875261 , -8.779148 , -8.65673  , -8.417706 , -8.413652 ,
       -8.1389   , -8.771584 , -5.971911 , -5.5967326, -8.295248 ,
       -7.665179 , -8.497422 , -8.813094 , -8.867477 , -8.928516 ,
       -8.8730755, -8.88836  , -8.921301 , -8.6270485], dtype=float32), 'input_ids': array([    2,    98,    25,    21,  1498,  4058,  6367,  1598,    29,
          14,    21,  1639,    60,     3,    21, 16439,  1448,    92,
          44,  6084,    28,    40,  9698,  1206,    16, 13946,   429,
          29,    21,  4295,    26,   352,  4851,     9,    14,  6367,
        3724,    26,    21, 16439,  1448,    25,  1870,    20,    28,
          21,  1448,  4851,    15,    17,   378,    52,    44,  4230,
          29,    14,  1448,  1145,     9,    19, 16439, 12745,  1639,
          15,    21,  1448,  3806,    20,    14,  8502,  1301,    20,
          44, 15091,     9,    19,  3710,    15,    40,  4851,    16,
          48,  1448,    25,    21,   864,  4105, 13326,  2416,    15,
          56,    92,  1884,    28,    14,  6367,    26,    21,  1401,
        1448,     9,    26,   823,    15,  3563,    14,  1448,    16,
       23513,   856,  4431,     9,    14,  4851,    25,    21,   234,
          13,     5,    62,     9,   263,     9,   357,     6,    17,
          14,  4295,    25,    13,     7,  1714,     7,   100,    14,
         234,    25,  1621,    17,    13,     7,   251,     7,  3190,
          13,     5,   108,    48,   610,    13,     7,   251,     7,
           6,     9,  1240,   226,   161,    15,    14,  4851,    25,
          21,  1498,  6367,    20,    14,  1448,    15,    17,    14,
        4295,    25,    14,  5196,  7265,    20,    14,   504,  6367,
           9,     3,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0], dtype=int32)}

**Comment by Danny-Google** [comment]
We have updated the code and add early stopping. Please let us know if you still encounter this problem. Thanks!

**Comment by skubicius** [comment]
Thanks for a quick reply!
The new squad_utils.py imports google_type_annotations which doesn’t seem to be available in google colab python 3.6.9.
Is there any way around it?

**Comment by skubicius** [comment]
My bad, the issue was caused by a cached tfrecord file which was generated with the previous version of the code.

After fixing that, I get the following results on dev-v2.0:
{
  "exact": 86.15345742440832,
  "f1": 89.20514892326143,
  "total": 11873,
  "HasAns_exact": 81.37651821862349,
  "HasAns_f1": 87.48865269330022,
  "HasAns_total": 5928,
  "NoAns_exact": 90.91673675357443,
  "NoAns_f1": 90.91673675357443,
  "NoAns_total": 5945
}

Thanks!
