### ISSUE TITLE
layer norm after embedding layer

### ISSUE THREAD

**Issue by taylorchu** [google-research/ALBERT#3]
https://github.com/google-research/ALBERT/blob/66bf3e950830048f65794f7b5644ff0ae7b5fab6/modeling.py#L617

Is there some benchmark that shows comparison with vs without this layer norm after embedding layer?

**Comment by 0x0539** [comment]
Not to my knowledge. It is the same as BERT: https://github.com/google-research/bert/blob/master/modeling.py#L520
