### ISSUE TITLE
The public score in readme comes from dev set or test set?

### ISSUE THREAD

**Issue by OleNet** [google-research/ALBERT#30]
I have a simple question: 

![image](https://user-images.githubusercontent.com/3206718/71151228-3ccc7280-226e-11ea-9120-17cda8325352.png)

Those scores in the readme, are those comes from dev set or test set?

Are they all median score of many times experiment?

**Comment by Danny-Google** [comment]
These are single run dev set results with early stopping.

**Comment by OleNet** [comment]
OK. Thank you!
