### ISSUE TITLE
Necessary readings to understand concepts used In ALBERT

### ISSUE THREAD

**Issue by satheeshravir** [google-research/ALBERT#47]
Please add list of recommended readings (books and research papers) to get a better understanding of the paper and its implementation. I am unable to add label. Please add documentation label to this issue

**Comment by 0x0539** [comment]
Sorry for the delayed response.
Can you provide more details about the problem you're having? Do you have some steps to reproduce?
If you have a question about a specific aspect of the paper, we can help you answer it. For general background reading, I recommend checking out the references section of the paper. You may also find the [Google AI Blog post on ALBERT](https://ai.googleblog.com/2019/12/albert-lite-bert-for-self-supervised.html) to be a good resource.
