### ISSUE TITLE
max_predictions_per_seq=20 for seq_len=512

### ISSUE THREAD

**Issue by YeDeming** [google-research/ALBERT#51]
Hi, 

Thanks for releasing the source code!

In the training script in Readme and create_pretraining_data.py/run_pretraining.py,

--max_seq_length=512 \
--max_predictions_per_seq=20 \

But 512*0.15=76.8 >> 20.

Which is the correct max predictions per seq number?

Thanks!

Best,
Deming Ye

**Comment by Danny-Google** [comment]
We use 20. Although the max_seq_length=512, we also have 10% of sequences that are shorter than 512. We follow BERT to use these settings and hasn't tuned them for ALBERT.

**Comment by YeDeming** [comment]
In original BERT's  readme and code,  max_predictions_per_seq=20 is for max_seq_length=128 while 128*0.15 = 19.2 ≈ 20

https://github.com/google-research/bert/blob/cc7051dc592802f501e8a6f71f8fb3cf9de95dc9/create_pretraining_data.py#L49-L51

**Comment by josecannete** [comment]
Same question, is not 0.15 of masked tokens then?

**Comment by Danny-Google** [comment]
We did do a few experiment on increasing the number of predictions, it seems that this parameter has marginal effect on the final results. But feel free to explore it further.
