### ISSUE TITLE
squad error

### ISSUE THREAD

**Issue by freefuiiismyname** [google-research/ALBERT#6]
i try to run run_squad_sp.py, and I met two error. :(((( my code is as follows:

```
python -m run_squad_sp \
    --albert_config_file=data/assets/albert_config.json \
    --vocab_file=data/assets/30k-clean.vocab \
    --spm_model_file=data/assets/30k-clean.model \
    --output_dir=data/output \
    --train_file=data/train-v2.0.json \
    --predict_file=data/dev-v2.0.json \
    --train_feature_file=data/train.tfrecord \
    --predict_feature_file=data/dev.tfrecord \
    --init_checkpoint=data/variables/variables \
    --do_train \
    --do_predict \
    --nouse_tpu \
    --train_batch_size=32 \
    --predict_batch_size=8 \
    --num_train_steps=3 \
    --version_2_with_negative=True
```

At first,it caused this error, and i had solued it.

> Traceback (most recent call last):
>   File "/home/bai/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/bai/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/bai/squad/run_squad_sp.py", line 1331, in <module>
>     tf.app.run()
>   File "/home/bai/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/home/bai/squad/run_squad_sp.py", line 1239, in main
>     output_fn=train_writer.process_feature)
>   File "/home/bai/squad/run_squad_sp.py", line 381, in convert_examples_to_features
>     print("".join(para_tokens))
> TypeError: sequence item 89: expected str instance, bytes found

Then i met other error.

> Traceback (most recent call last):
>   File "/home/bai/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/bai/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/bai/squad/run_squad_sp.py", line 1334, in <module>
>     tf.app.run()
>   File "/home/bai/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/home/bai/squad/run_squad_sp.py", line 1242, in main
>     output_fn=train_writer.process_feature)
>   File "/home/bai/squad/run_squad_sp.py", line 461, in convert_examples_to_features
>     n, is_start=False)
>   File "/home/bai/squad/run_squad_sp.py", line 302, in _convert_index
>     if index[pos] is not None:
> IndexError: list index out of range

May i get some help here, thx~

**Comment by YasinQiu** [comment]
I encountered the same problem, how did u fixed the 1st error?

**Comment by YasinQiu** [comment]
I encountered the same problem, how did you fix the 1st error?
`TypeError: sequence item 89: expected str instance, bytes found`

**Comment by ntedgi** [comment]
i have the same problem also 

@YasinQiu 
just add a quick and dirty  fix  
run_squad_sp.py line 381 
>     if type(para_tokens[89]) != str:
>                 para_tokens[89] = str(para_tokens[89] , 'utf-8')

**Comment by ZheyuYe** [comment]
@ntedgi the new lines fix the type bug on SQuAD2.0 remain the "list index out of range" for SQuAD1.1

**Comment by s4sarath** [comment]
```
        para_tokens = [six.ensure_text(token, "utf-8") for token in para_tokens]

```

Add the above line after line number 363 https://github.com/google-research/ALBERT/blob/master/run_squad_sp.py#L363 .
Try running it.

**Comment by Danny-Google** [comment]
The bug has been fixed. We also added early stopping. Please let us know if you encounter any further problems.

**Comment by freefuiiismyname** [comment]
@Danny-Google 
Thank you for your work on this issue.I've try to run the albert-base.I made the following slight changes,it does work now.

> with change line 29 in run_squad_v2.py.
> from garcon.albert import squad_utils  ——> import squad_utils
> 
> with del line 20 in squad_utils.py
> from __future__ import google_type_annotations

But I doubt the model was loaded.My running log is as follows:

> INFO:tensorflow:loading sentence piece model
> WARNING:tensorflow:Estimator's model_fn (<function v2_model_fn_builder.<locals>.model_fn at 0x7fae4f1e28c0>) includes params argument, but params are not passed to Estimator.
> INFO:tensorflow:Using config: {'_model_dir': 'data/output', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> graph_options {
>   rewrite_options {
>     meta_optimizer_iterations: ONE
>   }
> }
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fae4f32a910>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_cluster': None}
> INFO:tensorflow:_TPUContext: eval_on_tpu True
> WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
> INFO:tensorflow:***** Running training *****
> INFO:tensorflow:  Num orig examples = 130319
> INFO:tensorflow:  Batch size = 32
> INFO:tensorflow:  Num steps = 12217
> WARNING:tensorflow:From /home/rfj/.conda/envs/rfj/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From /opt/rfj/ALBERT-master/squad_utils.py:701: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.data.experimental.map_and_batch(...)`.
> WARNING:tensorflow:From /opt/rfj/ALBERT-master/squad_utils.py:678: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Running train on CPU
> INFO:tensorflow:*** Features ***
> INFO:tensorflow:  name = end_positions, shape = (32,)
> INFO:tensorflow:  name = input_ids, shape = (32, 384)
> INFO:tensorflow:  name = input_mask, shape = (32, 384)
> INFO:tensorflow:  name = is_impossible, shape = (32,)
> INFO:tensorflow:  name = p_mask, shape = (32, 384)
> INFO:tensorflow:  name = segment_ids, shape = (32, 384)
> INFO:tensorflow:  name = start_positions, shape = (32,)
> INFO:tensorflow:  name = unique_ids, shape = (32,)
> WARNING:tensorflow:From /opt/rfj/ALBERT-master/modeling.py:252: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dense instead.
> WARNING:tensorflow:From /opt/rfj/ALBERT-master/squad_utils.py:1550: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dropout instead.
> WARNING:tensorflow:From /home/rfj/.conda/envs/rfj/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
> INFO:tensorflow:name bert/embeddings/word_embeddings does not get matched
> INFO:tensorflow:name bert/embeddings/token_type_embeddings does not get matched
> INFO:tensorflow:name bert/embeddings/position_embeddings does not get matched
> INFO:tensorflow:name bert/embeddings/LayerNorm/beta does not get matched
> INFO:tensorflow:name bert/embeddings/LayerNorm/gamma does not get matched
> INFO:tensorflow:name bert/encoder/embedding_hidden_mapping_in/kernel does not get matched
> INFO:tensorflow:name bert/encoder/embedding_hidden_mapping_in/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/LayerNorm/beta does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/LayerNorm/gamma does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/kernel does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/bias does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/beta does not get matched
> INFO:tensorflow:name bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/gamma does not get matched
> INFO:tensorflow:name bert/pooler/dense/kernel does not get matched
> INFO:tensorflow:name bert/pooler/dense/bias does not get matched
> INFO:tensorflow:name start_logits/dense/kernel does not get matched
> INFO:tensorflow:name start_logits/dense/bias does not get matched
> INFO:tensorflow:name end_logits/dense_0/kernel does not get matched
> INFO:tensorflow:name end_logits/dense_0/bias does not get matched
> INFO:tensorflow:name end_logits/LayerNorm/beta does not get matched
> INFO:tensorflow:name end_logits/LayerNorm/gamma does not get matched
> INFO:tensorflow:name end_logits/dense_1/kernel does not get matched
> INFO:tensorflow:name end_logits/dense_1/bias does not get matched
> INFO:tensorflow:name answer_class/dense_0/kernel does not get matched
> INFO:tensorflow:name answer_class/dense_0/bias does not get matched
> INFO:tensorflow:name answer_class/dense_1/kernel does not get matched
> INFO:tensorflow:**** Trainable Variables ****
> INFO:tensorflow:  name = bert/embeddings/word_embeddings:0, shape = (30000, 128)
> INFO:tensorflow:  name = bert/embeddings/token_type_embeddings:0, shape = (2, 128)
> INFO:tensorflow:  name = bert/embeddings/position_embeddings:0, shape = (512, 128)
> INFO:tensorflow:  name = bert/embeddings/LayerNorm/beta:0, shape = (128,)
> INFO:tensorflow:  name = bert/embeddings/LayerNorm/gamma:0, shape = (128,)
> INFO:tensorflow:  name = bert/encoder/embedding_hidden_mapping_in/kernel:0, shape = (128, 768)
> INFO:tensorflow:  name = bert/encoder/embedding_hidden_mapping_in/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/kernel:0, shape = (768, 768)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/query/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/kernel:0, shape = (768, 768)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/key/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/kernel:0, shape = (768, 768)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/self/value/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/kernel:0, shape = (768, 768)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/attention_1/output/dense/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/LayerNorm/beta:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/LayerNorm/gamma:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/kernel:0, shape = (768, 3072)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/dense/bias:0, shape = (3072,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/kernel:0, shape = (3072, 768)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/ffn_1/intermediate/output/dense/bias:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/beta:0, shape = (768,)
> INFO:tensorflow:  name = bert/encoder/transformer/group_0/inner_group_0/LayerNorm_1/gamma:0, shape = (768,)
> INFO:tensorflow:  name = bert/pooler/dense/kernel:0, shape = (768, 768)
> INFO:tensorflow:  name = bert/pooler/dense/bias:0, shape = (768,)
> INFO:tensorflow:  name = start_logits/dense/kernel:0, shape = (768, 1)
> INFO:tensorflow:  name = start_logits/dense/bias:0, shape = (1,)
> INFO:tensorflow:  name = end_logits/dense_0/kernel:0, shape = (1536, 768)
> INFO:tensorflow:  name = end_logits/dense_0/bias:0, shape = (768,)
> INFO:tensorflow:  name = end_logits/LayerNorm/beta:0, shape = (768,)
> INFO:tensorflow:  name = end_logits/LayerNorm/gamma:0, shape = (768,)
> INFO:tensorflow:  name = end_logits/dense_1/kernel:0, shape = (768, 1)
> INFO:tensorflow:  name = end_logits/dense_1/bias:0, shape = (1,)
> INFO:tensorflow:  name = answer_class/dense_0/kernel:0, shape = (1536, 768)
> INFO:tensorflow:  name = answer_class/dense_0/bias:0, shape = (768,)
> INFO:tensorflow:  name = answer_class/dense_1/kernel:0, shape = (768, 1)
> WARNING:tensorflow:From /home/rfj/.conda/envs/rfj/lib/python3.7/site-packages/tensorflow/python/training/learning_rate_decay_v2.py:321: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.
> INFO:tensorflow:++++++ warmup starts at step 0, for 1221 steps ++++++
> INFO:tensorflow:using adamw
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> INFO:tensorflow:Graph was finalized.
> 2019-12-19 10:13:36.282285: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
> 2019-12-19 10:13:36.310368: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099975000 Hz
> 2019-12-19 10:13:36.312957: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x557b92d1ac60 executing computations on platform Host. Devices:
> 2019-12-19 10:13:36.313047: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
> 2019-12-19 10:13:36.523685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
> name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
> pciBusID: 0000:3b:00.0
> totalMemory: 22.38GiB freeMemory: 21.16GiB
> 2019-12-19 10:13:36.523761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
> 2019-12-19 10:13:36.526273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-12-19 10:13:36.526323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
> 2019-12-19 10:13:36.526341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
> 2019-12-19 10:13:36.527167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 20582 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:3b:00.0, compute capability: 6.1)
> 2019-12-19 10:13:36.546462: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x557b92026170 executing computations on platform CUDA. Devices:
> 2019-12-19 10:13:36.546635: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla P40, Compute Capability 6.1
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Saving checkpoints for 0 into data/output/model.ckpt.
> 2019-12-19 10:13:55.220011: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
> INFO:tensorflow:global_step/sec: 0.572434
> INFO:tensorflow:examples/sec: 18.3179

And my code is as follows:

> python -m run_squad_v2 \
> --albert_config_file=data/assets/albert_config.json \
> --vocab_file=data/assets/30k-clean.vocab \
> --spm_model_file=data/assets/30k-clean.model \
> --output_dir=data/output \
> --train_file=data/train-v2.0.json \
> --predict_file=data/dev-v2.0.json \
> --train_feature_file=data/train.tfrecord \
> --predict_feature_file=data/dev.tfrecord \
> --init_checkpoint=data/variables/variables.index \
> --do_train \
> --do_predict \
> --nouse_tpu \
> --train_batch_size=32 \
> --predict_batch_size=8 \
> --num_train_steps=3 \
> --version_2_with_negative=True
Is something wrong with my code?Hope for your reply.
Thank you for your effort again! ^ ^
