### ISSUE TITLE
Missing some weights parameters of the released albert_base_v2

### ISSUE THREAD

**Issue by shenlanyilang** [google-research/ALBERT#62]
I downloaded the pretrained albert model from link https://tfhub.dev/google/albert_base/2?tf-hub-format=compressed,   however I can't find parameters   cls/seq_relationship/output_weights  and cls/seq_relationship/output_bias  which defined in source code. 
I wan't to continue pretraining the model initializing from the released model in my specific corpus , so how can I get whole parameters?

**Comment by 0x0539** [comment]
See the `[Tar file]` links in the readme.
