### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by matteodelv** [google-research/ALBERT#68]
Is multi-GPU support expected to be implemented anytime soon?
What are the conceptual changes that need to be done in order to make ALBERT train/fine-tune on multiple GPUs?
Should `TPUEstimator` be replaced by `Estimator`, together with a distributed strategy such as `MirroredStrategy`?
Thank you so much!

**Comment by 0x0539** [comment]
Unfortunately, I don't think we'll be able to get to this anytime soon. Maybe one of the other ALBERT implementations will have it?

**Comment by apohllo** [comment]
https://github.com/kamalkraj/ALBERT-TF2.0 has support for multi-GPU pre-training
