### ISSUE TITLE
Issues with codes in Google Colab-Tensorflow-2.0.0

### ISSUE THREAD

**Issue by GaneshGS** [google-research/ALBERT#70]
Hi All,

I exported albert codes to google drive and mounted it into google colab. The code is not running due to many issues like tensorflow.contrib is not found etc. Could anybody suggest me how to run albert codes in google colab?

**Comment by 0x0539** [comment]
Only TF1.15 is supported at this time.
We don't have plans to support TF2.0 (yet).
See also: #112
