### ISSUE TITLE
[ALBERT] albert-xxlarge v1 `albert_config.josn/30k-clean.model` file

### ISSUE THREAD

**Issue by lsq357** [google-research/ALBERT#71]
Download albert-xxlarge-v1 from https://storage.googleapis.com/tfhub-modules/google/albert_xxlarge/1.tar.gz
there are only `30k-clean.model` file in v1's `assets`  dir,
But in albert-xxlarge-v2's `assets` dir, there are three files: `30k-clean.vocab` , `albert_config.json`, `30k-clean.model`.
How to get `30k-clean.vocab` , `albert_config.json` file in albert-xxlarge-v1  ??

**Comment by 0x0539** [comment]
@lsq357 The `30k-clean.vocab` file is no longer needed, only the `--spm_model_file`. The `albert_config.json` should be included in the .tar file now as well as the TF-Hub module. Please reopen if you still have any issues.
