### ISSUE TITLE
Model for SQuAD Question Answering

### ISSUE THREAD

**Issue by GaneshGS** [google-research/ALBERT#72]
Hi,
I would like to adopt the albert model ran for SQuAD data set. Is "run_squad_sp.py" a right model for this purpose? Is it enough if I run the code in this file alone else should I run any other .py files in the albert folder beforehand?

I was expecting some documentation for using the albert but not available unfortunately.

**Comment by vilas4485** [comment]
Can you please run run_squad_v2.py, as instructed on the repository home page? Thanks

**Comment by GaneshGS** [comment]
Thank you vilas! I'll try it.

**Comment by 0x0539** [comment]
Sorry about the delayed response. It took a little while to get our house in order :)
The readme now contains updated info on how to run the SQuAD benchmarks with ALBERT
