### ISSUE TITLE
[ALBERT] Failed to load TF-Hub model on Google Colab

### ISSUE THREAD

**Issue by xf05888** [google-research/ALBERT#90]
I want to import ALBERT in Google Colab so first I ran `bash albert/run.sh` to install albert
Then I import the model by the examples in README.md but get some error:
![Screenshot from 2019-11-08 22-07-18](https://user-images.githubusercontent.com/33285394/68482649-fe0dca80-0274-11ea-86cd-6062b4ddc470.png)
Seems like albert didn't import correctly, how can I slove it?

**Comment by 0x0539** [comment]
@xf05888 input_ids, input_mask, and segment_ids are the inputs to ALBERT.  As stated by the [TF-Hub docs](https://tfhub.dev/google/albert_base/3):

```
input_ids, input_mask, and segment_ids are int32 Tensors of shape [batch_size, max_sequence_length]
```

You can define them using `tf.placeholder`:
```
input_ids = tf.placeholder(dtype=tf.int32, shape=[batch_size, max_sequence_length])
```

Or by using the `tf.FixedLenFeature` when using TPU. See [here](https://github.com/google-research/ALBERT/blob/master/squad_utils.py#L657).
